name: SSB working dir
on: 
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: SetLocale
        run: |
          sudo locale-gen nb_NO
      - name: Update SSB
        env: 
          DW_TOKEN: ${{ secrets.DW_TOKEN }}
        run: python SSB_livslang_laring.py
      - name: Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
